### ISSUE TITLE
polusai/nyxus:0.2.2 not available on DockerHub

### ISSUE THREAD

**Issue by MyleneSimon** [PolusAI/nyxus#26]
Plugin manifest points to Docker image `polusai/nyxus:0.2.2`, but it looks like that version has not been pushed to DockerHub yet.

**Comment by hsidky** [comment]
Hi Mylene. This issue and #25  should be resolved. There should be a nyxus 0.2.3. Can you please test it and let us know if the issue remains?

**Comment by MyleneSimon** [comment]
Hi Hythem, just tested on our cluster and both issues are resolved indeed, thank you for releasing the new version.
